package com.example.passpoint.presentation.navigation

object NavigationRoutes  {
    const val SPLASH ="splash"
    const val ONBOARDING ="on boarding"
    const val SIGNIN ="sign in"
    const val SIGNUP ="sign up"
    const val MAIN ="main"
    const val PROFILE ="PROFILE"
    const val MINE ="MINE"
    const val CHANGEPASSWORD ="change password"
    const val OTP ="OTP"
    const val SETPASSWORD ="set password"
    const val NEWS ="News"
    const val NEWS_DETAIL = "news_detail"
    const val EVENTS = "events"
    const val PAST_EVENTS = "past_events"
    const val COURSES = "courses"
    const val PAST_COURSES = "past_courses"
    const val QR = "qr/{qrData}"
    const val USERS = "users"
    const val CREATE_EVENT = "create_event"
    const val CREATE_COURSE = "create_course"
    const val CREATE_NEWS = "create_news"
    const val EDIT_COURSE = "edit_course/{courseId}"
    const val EDIT_EVENT = "edit_event/{eventId}"
    const val EDIT_NEWS = "edit_news/{newsId}"
    const val EDIT_PROFILE = "edit_profile"
}